modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="more_tools"
version="0.0.1"
displayName="More Tools"
displayURL="https://modrinth.com/mod/more-advancements1.21+"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="XiaoMianbaoya2"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_tools]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.more_tools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.more_tools]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration